dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  mainnet-fork-dev:
    verify: False